export const MOUNTING_HOLE_DIAMETER_MM = 5
export const MOUNTING_HOLE_RADIUS_MM = MOUNTING_HOLE_DIAMETER_MM / 2
export const MOUNTING_HOLE_CENTER_INSET_MM = 7.5
export const TEXT_SAFE_PADDING_MM = 2
export const DEFAULT_FONT_SIZE_MM = 20
export const MIN_FONT_SIZE_MM = 4
export const MAX_FONT_SIZE_MM = 80
